# Generated by Django 4.0.7 on 2022-09-03 02:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_dob_alter_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dob',
            field=models.DateField(blank=True, default=datetime.date(2022, 9, 3), max_length=8, null=True),
        ),
    ]
