# Generated by Django 4.0.7 on 2022-09-03 02:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 9, 3, 2, 19, 42, 679180, tzinfo=utc), max_length=8, null=True),
        ),
    ]
